server:
  port: 81
  address: localhost
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/revideos?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password:
mybatis:
  mapper-locations: classpath:mappers/*.xml

# springdoc-openapi
springdoc:
  swagger-ui:
    path: /swgger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.github.kaguya1210.revideos_server

#knife4j????
knife4j:
  enable: true    #??knife4j?????@EnableKnife4j??
  setting:
    language: zh_cn   #??
    swagger-model-name: REVideos  #???SwaggerModel??,??
  #??Swagger?Basic????,???false
  basic:
    enable: false
    # Basic?????
    username: Kaguya
    # Basic????
    password: 123456
logging:
  level:
    root: error
    com:
      github:
        kaguya1210:
          revideos_server: debug